import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { pathToFileURL } from "node:url";
import test from "node:test";
import { build } from "esbuild";

test("dictation opt-in, native events, pinned insertion and cancellation", async (t) => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "pzza-dictation-test-"));
  const globals = new Map(["navigator", "localStorage", "window", "__dictationTest"].map((key) => [key, Object.getOwnPropertyDescriptor(globalThis, key)]));
  t.after(async () => {
    for (const [key, descriptor] of globals) {
      if (descriptor) Object.defineProperty(globalThis, key, descriptor);
      else delete globalThis[key];
    }
    await rm(dir, { recursive: true, force: true });
  });
  const storage = new Map();
  const window = new EventTarget();
  const notifications = [];
  window.addEventListener("pzza-notification", event => notifications.push(event.detail));
  Object.defineProperty(globalThis, "window", { configurable: true, value: window });
  Object.defineProperty(globalThis, "navigator", { configurable: true, value: { platform: "MacIntel", userAgent: "" } });
  Object.defineProperty(globalThis, "localStorage", { configurable: true, value: { getItem: (key) => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value) } });
  const listeners = new Map();
  const calls = [];
  let disconnected = false;
  let cancellationPending;
  let inputDevices = [
    { id: "built-in-mic", name: "Built-in microphone", isDefault: true },
    { id: "usb-mic", name: "USB microphone", isDefault: false },
  ];
  let inputDeviceError = false;
  globalThis.__dictationTest = {
    listen: async (event, callback) => { listeners.set(event, callback); return () => listeners.delete(event); },
    invoke: async (command, args) => {
      calls.push({ command, args });
      if (command === "speech_stop" && args.cancel) await cancellationPending;
      if (command === "speech_model_status") return { installed: false, downloading: false, downloadedBytes: 0, totalBytes: 100 };
      if (command === "speech_input_devices") {
        if (inputDeviceError) throw new Error("Could not list microphones");
        return inputDevices;
      }
      if (command === "speech_start" && disconnected) throw new Error("Microphone access denied");
      if (command === "speech_start" && args.inputDeviceId && !inputDevices.some(device => device.id === args.inputDeviceId)) throw new Error("Selected microphone is unavailable");
    },
  };
  const outfile = path.join(dir, "dictation.mjs");
  await build({ entryPoints: ["src/state/dictation.ts"], outfile, bundle: true, format: "esm", platform: "node", logLevel: "silent", plugins: [{ name: "native-test-boundary", setup(builder) {
    builder.onResolve({ filter: /^\.\/notifications$/ }, () => ({ path: "notifications", namespace: "notifications-test" }));
    builder.onLoad({ filter: /.*/, namespace: "notifications-test" }, () => ({ contents: 'export const notify = (detail) => window.dispatchEvent(new CustomEvent("pzza-notification", { detail }));', loader: "js" }));
    builder.onResolve({ filter: /^(?:@tauri-apps\/api\/(?:core|event)|\.\.\/tauriEnv)$/ }, (args) => ({ path: args.path, namespace: "native-test" }));
    builder.onLoad({ filter: /.*/, namespace: "native-test" }, () => ({ contents: "export const HAS_TAURI = true; export const invoke = (...args) => globalThis.__dictationTest.invoke(...args); export const listen = (...args) => globalThis.__dictationTest.listen(...args);", loader: "js" }));
  } }] });
  const { useDictation, initializeDictation, registerDictationTarget, dictationText } = await import(pathToFileURL(outfile).href);
  const emit = (event, payload) => listeners.get(event)({ payload });
  const flush = () => new Promise(resolve => setImmediate(resolve));
  assert.equal(useDictation.getState().enabled, false);
  await initializeDictation();
  assert.deepEqual(calls.map((call) => call.command), ["speech_model_status"]);
  assert.equal(useDictation.getState().model, "missing");
  await useDictation.getState().download();
  assert.equal(useDictation.getState().model, "downloading", "invoke acceptance must not mark download complete");
  await useDictation.getState().download();
  assert.equal(calls.filter((call) => call.command === "speech_model_download").length, 1);
  emit("dictation-download", { status: "downloading", downloadedBytes: 50, totalBytes: 100 });
  assert.equal(useDictation.getState().downloadedBytes, 50);
  emit("dictation-download", { status: "ready", downloadedBytes: 100, totalBytes: 100 });
  assert.equal(notifications.length, 1);
  assert.equal(notifications[0].event, "model-ready");
  assert.equal(useDictation.getState().model, "ready");
  assert.equal(storage.get("pzza.dictation.enabled"), "true");
  const inserted = [];
  const focused = [];
  const register = (tileId, insert) => registerDictationTarget(tileId, { insert, focus: () => focused.push(tileId) });
  const unregister = register("first", (text) => { inserted.push(text); return true; });
  register("second", () => { assert.fail("Transcript reached wrong terminal"); });
  await useDictation.getState().start("first");
  assert.deepEqual(focused, ["first"], "starting dictation focuses the target even if its tile is already active");
  const id = useDictation.getState().recording.id;
  assert.equal(calls.find(call => call.command === "speech_start").args.inputDeviceId, null, "new installations follow the system default microphone");
  emit("dictation", { id, kind: "listening" });
  assert.deepEqual(focused, ["first", "first"], "listening restores focus after microphone permission prompts");
  emit("dictation", { id, kind: "level", level: 0.4 });
  assert.equal(useDictation.getState().recording.level, 0.4);
  assert.equal(useDictation.getState().recording.processing, false);
  emit("dictation", { id, kind: "processing", active: true });
  assert.equal(useDictation.getState().recording.processing, true);
  assert.equal(useDictation.getState().recording.phase, "listening", "processing does not interrupt capture or change Stop behavior");
  emit("dictation", { id, kind: "level", level: 0.8 });
  assert.equal(useDictation.getState().recording.level, 0.8, "live input levels continue during decoding");
  emit("dictation", { id, kind: "processing", active: false });
  assert.equal(useDictation.getState().recording.processing, false);
  emit("dictation", { id, kind: "partial", text: "Merhaba world" });
  assert.equal(focused.length, 2, "audio updates do not repeatedly steal focus");
  assert.deepEqual(inserted, [], "partials must never be sent to terminal");
  await useDictation.getState().start("second");
  assert.equal(useDictation.getState().recording.id, id);
  await useDictation.getState().stop();
  assert.deepEqual(focused, ["first", "first", "first"], "stopping from a keyboard-focused control returns focus to the terminal");
  assert.equal(useDictation.getState().recording.phase, "finalizing");
  emit("dictation", { id, kind: "final", text: "Merhaba\nworld\r\u0003\u001b" });
  emit("dictation", { id, kind: "final", text: "duplicate event" });
  await flush();
  assert.deepEqual(inserted, ["Merhaba world"]);
  assert.equal(dictationText("Türkçe\u2028English\ttext\u009b"), "Türkçe English text");
  await useDictation.getState().start("first");
  const cancelled = useDictation.getState().recording.id;
  await useDictation.getState().cancel();
  emit("dictation", { id: cancelled, kind: "final", text: "late result" });
  emit("dictation", { id: cancelled, kind: "processing", active: true });
  await flush();
  assert.equal(useDictation.getState().recording, null, "late processing events cannot restore a cancelled recording");
  assert.deepEqual(inserted, ["Merhaba world"]);
  await useDictation.getState().start("first");
  const liveId = useDictation.getState().recording.id;
  emit("dictation", { id: liveId, kind: "listening" });
  emit("dictation", { id: liveId, kind: "partial", text: "First guess" });
  emit("dictation", { id: liveId, kind: "partial", text: "First sentence" });
  emit("dictation", { id: liveId, kind: "committed", text: "First sentence" });
  emit("dictation", { id: liveId, kind: "committed", text: "First sentence" });
  emit("dictation", { id: liveId, kind: "partial", text: "First sentence and more" });
  await flush();
  assert.deepEqual(inserted, ["Merhaba world", "First sentence"], "only stable text is inserted while listening, once");
  assert.equal(useDictation.getState().recording.committed, "First sentence");
  emit("dictation", { id: liveId, kind: "committed", text: "First sentence and more" });
  emit("dictation", { id: liveId, kind: "final", text: "First sentence and more words\n\u001b\u0003" });
  await flush();
  assert.deepEqual(inserted, ["Merhaba world", "First sentence", " and more", " words"], "final inserts only the remaining safe suffix");
  assert.equal(useDictation.getState().recording, null);
  await useDictation.getState().start("first");
  const silentId = useDictation.getState().recording.id;
  emit("dictation", { id: silentId, kind: "final", text: "" });
  await flush();
  assert.equal(useDictation.getState().recording.phase, "error");
  assert.match(useDictation.getState().recording.error, /No speech was recognized/);
  await useDictation.getState().cancel();
  await useDictation.getState().start("first");
  const previewId = useDictation.getState().recording.id;
  emit("dictation", { id: previewId, kind: "partial", text: "Keep this preview" });
  emit("dictation", { id: previewId, kind: "final", text: "" });
  await flush();
  assert.equal(useDictation.getState().recording.text, "Keep this preview");
  assert.match(useDictation.getState().recording.error, /before it could confirm the remaining words/);
  assert.deepEqual(inserted, ["Merhaba world", "First sentence", " and more", " words"], "empty final events never silently discard or insert provisional text");
  await useDictation.getState().cancel();
  await useDictation.getState().start("first");
  unregister();
  assert.equal(useDictation.getState().recording, null, "closing target cancels recording");
  let failingWrites = 0;
  register("first", async () => { failingWrites++; throw new Error("PTY disconnected"); });
  await useDictation.getState().start("first");
  const failedId = useDictation.getState().recording.id;
  emit("dictation", { id: failedId, kind: "committed", text: "Keep this transcript" });
  emit("dictation", { id: failedId, kind: "final", text: "Keep this transcript intact" });
  await flush();
  assert.equal(failingWrites, 1, "failed delivery must never retry an uncertain write");
  assert.equal(useDictation.getState().recording.phase, "error");
  assert.equal(useDictation.getState().recording.text, "Keep this transcript intact", "queued final text remains recoverable after an uncertain write fails");
  assert.match(useDictation.getState().recording.error, /PTY disconnected/);
  emit("dictation", { id: failedId, kind: "processing", active: true });
  emit("dictation", { id: failedId, kind: "listening" });
  assert.equal(useDictation.getState().recording.phase, "error");
  assert.equal(useDictation.getState().recording.processing, false, "late native activity cannot revive a failed recording");
  assert.ok(calls.some(call => call.command === "speech_stop" && call.args.id === failedId && call.args.cancel));
  await useDictation.getState().cancel();
  disconnected = true;
  register("first", () => true);
  await useDictation.getState().start("first");
  assert.match(useDictation.getState().recording.error, /Microphone access denied/);
  useDictation.getState().setEnabled(false);
  assert.equal(useDictation.getState().recording, null);
  assert.equal(storage.get("pzza.dictation.enabled"), "false");

  disconnected = false;
  const refresh = useDictation.getState().refreshInputDevices();
  await Promise.all([refresh, useDictation.getState().refreshInputDevices()]);
  assert.equal(calls.filter(call => call.command === "speech_input_devices").length, 1, "concurrent device refreshes share one native request");
  assert.deepEqual(useDictation.getState().inputDevices, inputDevices);
  useDictation.getState().setInputDevice("usb-mic");
  assert.deepEqual(JSON.parse(storage.get("pzza.dictation.inputDevice")), { id: "usb-mic", name: "USB microphone" });
  useDictation.getState().setInputDevice("unknown-mic");
  assert.equal(useDictation.getState().inputDevice.id, "usb-mic");
  useDictation.getState().setEnabled(true);
  await useDictation.getState().start("first");
  assert.equal(calls.filter(call => call.command === "speech_start").at(-1).args.inputDeviceId, "usb-mic");
  useDictation.getState().setInputDevice(null);
  assert.equal(useDictation.getState().inputDevice.id, "usb-mic", "recording pins the selected microphone");
  await useDictation.getState().cancel();

  inputDevices = inputDevices.slice(0, 1);
  await useDictation.getState().refreshInputDevices();
  assert.equal(useDictation.getState().inputDevice.id, "usb-mic", "unplugging a microphone never silently switches the saved choice");
  await useDictation.getState().start("first");
  assert.match(useDictation.getState().recording.error, /Selected microphone is unavailable/);
  await useDictation.getState().cancel();
  inputDeviceError = true;
  await useDictation.getState().refreshInputDevices();
  assert.match(useDictation.getState().inputDevicesError, /Could not list microphones/);
  assert.equal(useDictation.getState().model, "ready", "device errors do not mark the speech model as broken");
  inputDeviceError = false;
  await useDictation.getState().refreshInputDevices();
  assert.equal(useDictation.getState().inputDevicesError, null);

  const restored = await import(`${pathToFileURL(outfile).href}?restored`);
  assert.deepEqual(restored.useDictation.getState().inputDevice, { id: "usb-mic", name: "USB microphone" }, "the microphone choice survives an app restart");
  useDictation.getState().setInputDevice(null);
  await useDictation.getState().start("first");
  assert.equal(calls.filter(call => call.command === "speech_start").at(-1).args.inputDeviceId, null);
  await useDictation.getState().cancel();
  storage.set("pzza.dictation.inputDevice", '{"id":42}');
  const invalidPreference = await import(`${pathToFileURL(outfile).href}?invalid`);
  assert.equal(invalidPreference.useDictation.getState().inputDevice, null);

  await useDictation.getState().start("first");
  const loadingId = useDictation.getState().recording.id;
  assert.equal(useDictation.getState().recording.phase, "loading");
  await useDictation.getState().stop();
  assert.equal(useDictation.getState().recording, null, "Stop cancels microphone preparation");
  assert.ok(calls.some(call => call.command === "speech_stop" && call.args.id === loadingId && call.args.cancel));
  emit("dictation", { id: loadingId, kind: "listening" });
  emit("dictation", { id: loadingId, kind: "committed", text: "cancelled startup" });
  await flush();
  assert.equal(useDictation.getState().recording, null, "late events cannot revive cancelled capture");

  await useDictation.getState().start("first");
  const stoppingId = useDictation.getState().recording.id;
  emit("dictation", { id: stoppingId, kind: "listening" });
  await useDictation.getState().stop();
  assert.equal(useDictation.getState().recording.phase, "finalizing");
  await useDictation.getState().stop();
  assert.equal(useDictation.getState().recording, null, "Stop can cancel an in-progress final transcription");
  assert.ok(calls.some(call => call.command === "speech_stop" && call.args.id === stoppingId && call.args.cancel));
  emit("dictation", { id: stoppingId, kind: "final", text: "cancelled finalization" });
  await flush();
  await useDictation.getState().start("first");
  assert.equal(useDictation.getState().recording.phase, "loading", "a new recording can follow cancellation");
  await useDictation.getState().cancel();

  await useDictation.getState().start("first");
  let finishCancellation;
  cancellationPending = new Promise(resolve => { finishCancellation = resolve; });
  const cancelling = useDictation.getState().stop();
  const startsBeforeRestart = calls.filter(call => call.command === "speech_start").length;
  const restarting = useDictation.getState().start("first");
  await flush();
  assert.equal(useDictation.getState().recording.phase, "loading");
  assert.equal(calls.filter(call => call.command === "speech_start").length, startsBeforeRestart, "a rapid restart waits for native cancellation to finish");
  finishCancellation();
  await Promise.all([cancelling, restarting]);
  cancellationPending = undefined;
  assert.equal(calls.filter(call => call.command === "speech_start").length, startsBeforeRestart + 1);
  await useDictation.getState().cancel();
});
