use std::net::TcpStream;
use std::process::Command;
use std::time::Duration;

// Launches the remote Linux desktop over RDP: an ssh tunnel exposes the
// firewalled remote 3389 on a local port, the RDP password is read from the
// login Keychain at launch (never stored here), and a bundled/homebrew
// sdl-freerdp connects with the pinned cert fingerprint.
#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RdpOptions {
    host: String,
    tunnel_port: u16,
    remote_port: u16,
    user: String,
    cert_fingerprint: String,
    keychain_service: String,
    freerdp_bin: String,
}

fn tunnel_up(port: u16) -> bool {
    let addr = format!("127.0.0.1:{port}");
    match addr.parse() {
        Ok(sa) => TcpStream::connect_timeout(&sa, Duration::from_millis(400)).is_ok(),
        Err(_) => false,
    }
}

// Report whether the RDP tunnel's local port is already listening.
#[tauri::command]
pub fn rdp_status(tunnel_port: u16) -> bool {
    tunnel_up(tunnel_port)
}

fn ensure_tunnel(host: &str, tunnel_port: u16, remote_port: u16) -> Result<(), String> {
    if tunnel_up(tunnel_port) {
        return Ok(());
    }
    let spec = format!("127.0.0.1:{tunnel_port}:127.0.0.1:{remote_port}");
    let status = Command::new("ssh")
        .args([
            "-f",
            "-N",
            "-o",
            "ExitOnForwardFailure=yes",
            "-o",
            "ConnectTimeout=10",
            "-L",
            &spec,
            host,
        ])
        .status()
        .map_err(|e| e.to_string())?;
    if status.success() {
        Ok(())
    } else {
        Err("SSH tunnel to the devbox failed. Is it reachable?".to_string())
    }
}

fn keychain_password(service: &str) -> Result<String, String> {
    let out = Command::new("security")
        .args(["find-generic-password", "-s", service, "-w"])
        .output()
        .map_err(|e| e.to_string())?;
    if !out.status.success() {
        return Err(format!("Keychain entry '{service}' not found."));
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

fn ssh_base(port: Option<u16>, identity: &Option<String>) -> Vec<String> {
    let mut args = vec![
        "-o".into(),
        "BatchMode=yes".into(),
        "-o".into(),
        "ConnectTimeout=12".into(),
        "-o".into(),
        "StrictHostKeyChecking=accept-new".into(),
    ];
    if let Some(p) = port {
        args.push("-p".into());
        args.push(p.to_string());
    }
    if let Some(id) = identity {
        if !id.trim().is_empty() {
            args.push("-i".into());
            args.push(id.clone());
        }
    }
    args
}

// Provision GNOME Remote Desktop on a target device over SSH: enable RDP with
// the given credentials, ensure a self-signed TLS cert, start the service, and
// return the cert's SHA-256 fingerprint. Credentials are generated by the app;
// user/password are alphanumeric so they need no shell escaping beyond quoting.
#[tauri::command]
pub fn rdp_provision(
    target: String,
    port: Option<u16>,
    identity: Option<String>,
    user: String,
    password: String,
) -> Result<String, String> {
    if user.chars().any(|c| !c.is_ascii_alphanumeric())
        || password.chars().any(|c| !c.is_ascii_alphanumeric())
    {
        return Err("credentials must be alphanumeric".into());
    }
    let remote = format!(
        r#"set -e
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
if ! command -v grdctl >/dev/null 2>&1; then echo "ERROR: gnome-remote-desktop (grdctl) not installed"; exit 3; fi
grdctl rdp enable
grdctl rdp set-credentials '{user}' '{password}'
grdctl rdp disable-view-only || true
D="$HOME/.local/share/gnome-remote-desktop"; mkdir -p "$D"
if [ ! -f "$D/rdp-tls.crt" ]; then
  openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj "/CN=pzzacode-$(hostname)" -out "$D/rdp-tls.crt" -keyout "$D/rdp-tls.key" >/dev/null 2>&1
fi
grdctl rdp set-tls-cert "$D/rdp-tls.crt"
grdctl rdp set-tls-key "$D/rdp-tls.key"
systemctl --user enable --now gnome-remote-desktop.service >/dev/null 2>&1 || true
systemctl --user restart gnome-remote-desktop.service >/dev/null 2>&1 || true
echo "FP:$(openssl x509 -in "$D/rdp-tls.crt" -noout -fingerprint -sha256 | sed 's/.*=//; s/://g')""#
    );
    let mut args = ssh_base(port, &identity);
    args.push(target);
    args.push(remote);
    let out = Command::new("ssh")
        .args(&args)
        .output()
        .map_err(|e| e.to_string())?;
    let stdout = String::from_utf8_lossy(&out.stdout);
    let stderr = String::from_utf8_lossy(&out.stderr);
    let fp = stdout
        .lines()
        .filter_map(|l| l.strip_prefix("FP:"))
        .map(|s| s.trim().to_string())
        .find(|s| s.len() == 64 && s.chars().all(|c| c.is_ascii_hexdigit()));
    match fp {
        Some(f) => Ok(f),
        None => Err(format!(
            "RDP provisioning failed. {}{}",
            stderr.trim(),
            stdout.trim()
        )),
    }
}

// Store an RDP password in the login Keychain (created/updated), so rdp_launch
// can read it later without the app ever persisting it in plaintext.
#[tauri::command]
pub fn keychain_set(service: String, account: String, password: String) -> Result<(), String> {
    let status = Command::new("security")
        .args([
            "add-generic-password",
            "-U",
            "-s",
            &service,
            "-a",
            &account,
            "-w",
            &password,
        ])
        .status()
        .map_err(|e| e.to_string())?;
    if status.success() {
        Ok(())
    } else {
        Err("could not write to Keychain".into())
    }
}

// Open the RDP desktop in its own sdl-freerdp window. The window is external by
// design; in-tile embedding is a later phase.
#[tauri::command]
pub fn rdp_launch(opts: RdpOptions) -> Result<(), String> {
    ensure_tunnel(&opts.host, opts.tunnel_port, opts.remote_port)?;
    let password = keychain_password(&opts.keychain_service)?;

    // Argument set chosen for consistent, reliable RDP behavior.
    Command::new(&opts.freerdp_bin)
        .arg(format!("/v:127.0.0.1:{}", opts.tunnel_port))
        .arg(format!("/u:{}", opts.user))
        .arg(format!("/p:{password}"))
        .arg("/ipv4:force")
        .arg(format!(
            "/cert:fingerprint:sha256:{}",
            opts.cert_fingerprint
        ))
        .arg("/dynamic-resolution")
        .arg("/network:lan")
        .arg("/gfx:AVC444")
        .arg("-compression")
        .arg("+clipboard")
        .spawn()
        .map_err(|e| format!("could not launch sdl-freerdp: {e}"))?;
    Ok(())
}
